steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/flask-repo/mi-api-flask', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/flask-repo/mi-api-flask']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'mi-api-flask', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/flask-repo/mi-api-flask', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
